var f;f||=typeof Module !== 'undefined' ? Module : {};var aa=Object.assign({},f),g=(a,b)=>{throw b;},ba="object"==typeof window,m="function"==typeof importScripts,n="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,ca=f.$ww,_scriptDir="undefined"!=typeof document&&document.currentScript?document.currentScript.src:void 0;m?_scriptDir=self.location.href:n&&(_scriptDir=__filename);var u="";
function da(a){return f.locateFile?f.locateFile(a,u):u+a}var ea,x,y;
if(n){var fs=require("fs"),fa=require("path");u=m?fa.dirname(u)+"/":__dirname+"/";ea=(b,c)=>{b=z(b)?new URL(b):fa.normalize(b);return fs.readFileSync(b,c?void 0:"utf8")};y=b=>{b=ea(b,!0);b.buffer||(b=new Uint8Array(b));return b};x=(b,c,d,e=!0)=>{b=z(b)?new URL(b):fa.normalize(b);fs.readFile(b,e?void 0:"utf8",(k,h)=>{k?d(k):c(e?h.buffer:h)})};process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);process.on("uncaughtException",b=>{if(!("unwind"===b||b instanceof A||b.context instanceof
A))throw b;});g=(b,c)=>{process.exitCode=b;throw c;};f.inspect=()=>"[Emscripten Module object]";let a;try{a=require("worker_threads")}catch(b){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),b;}global.Worker=a.Worker}else if(ba||m)m?u=self.location.href:"undefined"!=typeof document&&document.currentScript&&(u=document.currentScript.src),u=0!==u.indexOf("blob:")?u.substr(0,u.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ea=
a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},m&&(y=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),x=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};f.print||console.log.bind(console);var C=f.printErr||console.error.bind(console);Object.assign(f,aa);
aa=null;f.quit&&(g=f.quit);var D;f.wasmBinary&&(D=f.wasmBinary);"object"!=typeof WebAssembly&&ha("no native wasm support detected");var E,ka,la=!1,ma,F,na,G,H,I,J,oa=f.INITIAL_MEMORY||16777216;
if(f.wasmMemory)E=f.wasmMemory;else if(E=new WebAssembly.Memory({initial:oa/65536,maximum:oa/65536,shared:!0}),!(E.buffer instanceof SharedArrayBuffer))throw C("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),n&&C("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)"),Error("bad memory");
var K=E.buffer;f.HEAP8=ma=new Int8Array(K);f.HEAP16=na=new Int16Array(K);f.HEAPU8=F=new Uint8Array(K);f.HEAPU16=new Uint16Array(K);f.HEAP32=G=new Int32Array(K);f.HEAPU32=H=new Uint32Array(K);f.HEAPF32=I=new Float32Array(K);f.HEAPF64=J=new Float64Array(K);oa=E.buffer.byteLength;var pa=[],qa=[],ra=[],sa=[],ta=[];function ua(){if(ca){let a=f;va(a.sb,a.sz);removeEventListener("message",wa);xa=xa.forEach(ya);addEventListener("message",ya)}else za(qa)}
function Aa(){var a=f.preRun.shift();pa.unshift(a)}var L=0,Ba=null,M=null;function ha(a){f.onAbort?.(a);a="Aborted("+a+")";C(a);la=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Ca=a=>a.startsWith("data:application/octet-stream;base64,"),z=a=>a.startsWith("file://"),N;N="app.wasm";Ca(N)||(N=da(N));function Da(a){if(a==N&&D)return new Uint8Array(D);if(y)return y(a);throw"both async and sync fetching of the wasm failed";}
function Ea(a){if(!D&&(ba||m)){if("function"==typeof fetch&&!z(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Da(a));if(x)return new Promise((b,c)=>{x(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Da(a))}function Fa(a,b,c){return Ea(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{C(`failed to asynchronously prepare wasm: ${d}`);ha(d)})}
function Ga(a,b){var c=N;D||"function"!=typeof WebAssembly.instantiateStreaming||Ca(c)||z(c)||n||"function"!=typeof fetch?Fa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){C(`wasm streaming compile failed: ${e}`);C("falling back to ArrayBuffer instantiation");return Fa(c,a,b)}))}
var Ha={2322:function(){let a=Atomics.waitAsync(G,arguments[0]>>2,arguments[1]),b=Array.prototype.slice.call(arguments,4,arguments.length),c=arguments[2]>>2,d=arguments[3],e=0==b.length?"":"i".repeat(b.length);a.async&&a.value.then(()=>{console.log("promise finished");f.dynCall("v"+e,d,b)});G[c]=!!a.async}};function A(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var xa=[],Ia=[],Ja,O=a=>{var b=Ia[a];b||(a>=Ia.length&&(Ia.length=a+1),Ia[a]=b=Ja.get(a));return b},ya=a=>{a=n?a:a.data;let b=a._wsc;b&&O(b)(...a.x)},wa=a=>{xa.push(a)},za=a=>{for(;0<a.length;)a.shift()(f)},Ka=f.noExitRuntime||!0,La={},Ma=1,Na=[],Oa=0;function Pa(){for(var a=P.length-1;0<=a;--a)Qa(a);P=[];Ra=[]}var Ra=[];function Sa(){if(navigator.userActivation?navigator.userActivation.isActive:Oa&&Ta.o)for(var a=0;a<Ra.length;++a){var b=Ra[a];Ra.splice(a,1);--a;b.D.apply(null,b.B)}}var P=[];
function Qa(a){var b=P[a];b.target.removeEventListener(b.g,b.A,b.j);P.splice(a,1)}function Ua(a){function b(d){++Oa;Ta=a;Sa();a.m(d);Sa();--Oa}if(!a.target)return-4;if(a.l)a.A=b,a.target.addEventListener(a.g,b,a.j),P.push(a),Va||(sa.push(Pa),Va=!0);else for(var c=0;c<P.length;++c)P[c].target==a.target&&P[c].g==a.g&&Qa(c--);return 0}
var Va,Ta,Wa,Xa,Ya,Za="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,Q=a=>{if(a){for(var b=a+NaN,c=a;F[c]&&!(c>=b);)++c;if(16<c-a&&F.buffer&&Za)a=Za.decode(F.buffer instanceof SharedArrayBuffer?F.slice(a,c):F.subarray(a,c));else{for(b="";a<c;){var d=F[a++];if(d&128){var e=F[a++]&63;if(192==(d&224))b+=String.fromCharCode((d&31)<<6|e);else{var k=F[a++]&63;d=224==(d&240)?(d&15)<<12|e<<6|k:(d&7)<<18|e<<12|k<<6|F[a++]&63;65536>d?b+=String.fromCharCode(d):(d-=65536,b+=String.fromCharCode(55296|
d>>10,56320|d&1023))}}else b+=String.fromCharCode(d)}a=b}}else a="";return a},$a=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],ab=a=>{a=2<a?Q(a):a;return $a[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},bb=a=>0>$a.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},db=(a,b,c,d)=>{Wa||=cb(36);a=ab(a);return Ua({target:a,g:"resize",l:d,m:(e=event)=>{if(e.target==a){var k=document.body;if(k){var h=Wa;G[h>>2]=e.detail;G[h+4>>2]=k.clientWidth;G[h+
8>>2]=k.clientHeight;G[h+12>>2]=innerWidth;G[h+16>>2]=innerHeight;G[h+20>>2]=outerWidth;G[h+24>>2]=outerHeight;G[h+28>>2]=pageXOffset;G[h+32>>2]=pageYOffset;O(d)(10,h,b)&&e.preventDefault()}}},j:c})},eb=(a,b,c,d,e,k)=>{Xa||=cb(1696);a=ab(a);return Ua({target:a,o:"touchstart"==k||"touchend"==k,g:k,l:d,m:h=>{for(var l,q={},t=h.touches,r=0;r<t.length;++r)l=t[r],l.s=l.u=0,q[l.identifier]=l;for(r=0;r<h.changedTouches.length;++r)l=h.changedTouches[r],l.s=1,q[l.identifier]=l;for(r=0;r<h.targetTouches.length;++r)q[h.targetTouches[r].identifier].u=
1;t=Xa;J[t>>3]=h.timeStamp;var p=t>>2;G[p+3]=h.ctrlKey;G[p+4]=h.shiftKey;G[p+5]=h.altKey;G[p+6]=h.metaKey;p+=7;var v=bb(a),B=0;for(r in q)if(l=q[r],G[p]=l.identifier,G[p+1]=l.screenX,G[p+2]=l.screenY,G[p+3]=l.clientX,G[p+4]=l.clientY,G[p+5]=l.pageX,G[p+6]=l.pageY,G[p+7]=l.s,G[p+8]=l.u,G[p+9]=l.clientX-v.left,G[p+10]=l.clientY-v.top,p+=13,31<++B)break;G[t+8>>2]=B;O(d)(e,t,b)&&h.preventDefault()},j:c})},fb=(a,b,c,d)=>{Ya||=cb(104);return Ua({target:a,o:!0,g:"wheel",l:d,m:(e=event)=>{var k=Ya;J[k>>3]=
e.timeStamp;var h=k>>2;G[h+2]=e.screenX;G[h+3]=e.screenY;G[h+4]=e.clientX;G[h+5]=e.clientY;G[h+6]=e.ctrlKey;G[h+7]=e.shiftKey;G[h+8]=e.altKey;G[h+9]=e.metaKey;na[2*h+20]=e.button;na[2*h+21]=e.buttons;G[h+11]=e.movementX;G[h+12]=e.movementY;var l=bb(a);G[h+13]=e.clientX-l.left;G[h+14]=e.clientY-l.top;J[k+72>>3]=e.deltaX;J[k+80>>3]=e.deltaY;J[k+88>>3]=e.deltaZ;G[k+96>>2]=e.deltaMode;O(d)(9,k,b)&&e.preventDefault()},j:c})};
String.prototype.replaceAll||(String.prototype.replaceAll=function(a,b){"?"===a&&(a="\\?");return this.replace(a instanceof RegExp?a:new RegExp(a,"g"),b)});function R(a,b,c){c=c||65;for(b=b.split("|");b[0];)a=a.replaceAll(String.fromCharCode(c++),b.pop());return[,].concat(a.split(" "))}
var S=R("r8YA8TA8SA8UALSALUALWR8YR8TR8SR8UANSANUANWRLSRLURLW V8Y V8Z V8T V8S V8U bgra8Y bgra8ZRb9e5uWRbJa2SRbJa2YR11bJuWRNSRNURNW VLS VLU VLW VNS VNU VNWB8ILYI24plusI24plus-E8INWINW-E8Q1-V-YQ1-V-ZQ2-V-YQ2-V-ZQ3-V-YQ3-V-ZQ4-r-YQ4-r-TQ5-rg-YQ5-rg-TQ6h-rgb-uWQ6h-rgb-WQ7-V-YQ7-V-ZPYPZPa1YPa1Z etc2-V8Y etc2-V8ZFr11YFr11TFrg11YFrg11TX4x4-YX4x4-ZX5x4-YX5x4-ZX5x5-YX5x5-ZX6x5-YX6x5-ZX6x6-YX6x6-ZX8x5-YX8x5-ZX8x6-YX8x6-ZX8x8-YX8x8-ZXJx5-YXJx5-ZXJx6-YXJx6-ZXJx8-YXJx8-ZXJxJ-YXJxJ-ZX12xJ-YX12xJ-ZX12x12-YX12x12-Z S8MS8KU8MU8KY8MY8KT8MT8KSLMSLKULMULKYLMYLKTLMTLKWLMWLKWN WNMWNx3 WNKSN SNMSNx3 SNKUN UNMUNx3 UNKYJ-J-J-2","unorm-srgb|unorm| astc-|float|rgba|sint|snorm|uint| rg| bc| etc2-rgb8|-AC|32|x2 |16|x4 |10| depth|-B|SC| eac-|stencil|-ESJ|-E-A| E| r"),
T={},U=1;function V(a){if(a){for(;T[++U];)2147483646<U&&(U=1);T[U]=a;return a.v=U}}function gb(a){return b=>{try{return a(b)}catch(c){}}}
var hb=R("B-clip-control B32D-Aencil8EbcEetc2EaAc timeAamp-query indirect-firA-inAance shader-f16 rg11b10uD-rendC bgra8unorm-Aorage D32-filtC"," texture-compression-|float|erable|depth|st").slice(1),ib=R(">1D >2D >3D maxTextureArrayLayer<6<6sPlus7=<BindingsPer6 maxDynamicUniform=;DynamicS:=;SampledTexture@maxSampler@maxS:=@maxS:Texture@maxUniform=@minUniform=9inS:=9ax7=<7Attribute<7=ArrayStride max8Component<8Variable<ColorAttachment<ColorAttachmentBytesPerSample?pS:Size maxComputeInvocationsPerWorkgroup?pSizeX?pSizeY?pSizeZ","sPerShaderStage | maxComputeWorkgrou|maxTextureDimension|Buffer|s max|sPerPipelineLayout max|torage|OffsetAlignment m|InterStageShader|Vertex|BindGroup|Uniform7|8ColorAttachmen",
52).slice(1),jb=R("maxUniform4Storage4BufferSize","BufferBindingSize max",52).slice(1);function W(a){return H[a]+4294967296*H[a+1]}var kb=[,"srgb","display-p3"];function X(a){let b=T[a];b&&(b.destroy&&b.destroy(),b.h&&b.h.forEach(X),delete T[a])}var lb=[,"load","clear"],mb=[,"store","discard"];function Y(a,b){(a=V(a))&&b.h.push(a);return a}var nb=R("neverA equalACB notCBCalways","-equal |greater| less"),ob=R("keep zero replace invert inCBdeCBinCA deCA","crement-|clamp |wrap");
function pb(a){return{compare:nb[H[a]],failOp:ob[H[a+1]],depthFailOp:ob[H[a+2]],passOp:ob[H[a+3]]}}var qb=R("add Areverse-Amin max","subtract "),rb=R("zero one BEB BDEBD AEA ADEAD BD-saturated CEC"," one-minus-|-alpha|constant|src|dst");function sb(a){return{operation:qb[H[a]],srcFactor:rb[H[a+1]],dstFactor:rb[H[a+2]]}}function tb(a,b){let c={};for(;b--;)c[Q(H[a>>2])]=J[a+8>>3],a+=16;return c}var ub=R("A16 A32","uint"),vb=R("pointDADAB CDCB","-list |triangle|-strip|line");
function wb(a){var b=[];let c=[],d=a>>2,e=G[d+2],k=H[d+3]>>2,h=d+6;a=h+5;let l=a+17,q=l+3,t=G[q+2],r=H[q+3]>>2,p=H[a++],v=H[l],B=H[q],w=H[q+6];for(;e--;){let ia=[],Gb=G[k],ja=H[k+1]>>2;for(;Gb--;)ia.push({offset:W(ja),shaderLocation:H[ja+2],format:S[H[ja+3]]}),ja+=4;b.push({arrayStride:W(k+2),stepMode:[,"vertex","instance"][H[k+4]],attributes:ia});k+=6}for(;t--;)c.push(H[r]?{format:S[H[r]],blend:H[r+1]?{color:sb(r+1),alpha:sb(r+4)}:void 0,writeMask:H[r+7]}:null),r+=8;b={vertex:{module:T[H[d]],entryPoint:Q(H[d+
1])||void 0,buffers:b,constants:tb(H[d+5],G[d+4])},primitive:{topology:vb[H[h]],stripIndexFormat:ub[H[h+1]],frontFace:[,"ccw","cw"][H[h+2]],cullMode:[,"none","front","back"][H[h+3]],unclippedDepth:!!H[h+4]},layout:1<w?T[w]:"auto"};p&&(b.depthStencil={format:S[p],depthWriteEnabled:!!H[a++],depthCompare:nb[H[a++]],stencilReadMask:H[a++],stencilWriteMask:H[a++],depthBias:G[a++],depthBiasSlopeScale:I[a++],depthBiasClamp:I[a++],stencilFront:pb(a),stencilBack:pb(a+4),clampDepth:!!H[a+8]});v&&(b.multisample=
{count:v,mask:H[l+1],alphaToCoverageEnabled:!!H[l+2]});B&&(b.fragment={module:T[B],entryPoint:Q(H[q+1])||void 0,targets:c,constants:tb(H[q+5],G[q+4])});return b}
var Ab=(a,b,c,d)=>{var e={string:t=>{var r=0;if(null!==t&&void 0!==t&&0!==t){for(var p=r=0;p<t.length;++p){var v=t.charCodeAt(p);127>=v?r++:2047>=v?r+=2:55296<=v&&57343>=v?(r+=4,++p):r+=3}v=r+1;p=r=xb(v);if(0<v){v=p+v-1;for(var B=0;B<t.length;++B){var w=t.charCodeAt(B);if(55296<=w&&57343>=w){var ia=t.charCodeAt(++B);w=65536+((w&1023)<<10)|ia&1023}if(127>=w){if(p>=v)break;F[p++]=w}else{if(2047>=w){if(p+1>=v)break;F[p++]=192|w>>6}else{if(65535>=w){if(p+2>=v)break;F[p++]=224|w>>12}else{if(p+3>=v)break;
F[p++]=240|w>>18;F[p++]=128|w>>12&63}F[p++]=128|w>>6&63}F[p++]=128|w&63}}F[p]=0}}return r},array:t=>{var r=xb(t.length);ma.set(t,r);return r}};a=f["_"+a];var k=[],h=0;if(d)for(var l=0;l<d.length;l++){var q=e[c[l]];q?(0===h&&(h=yb()),k[l]=q(d[l])):k[l]=d[l]}c=a.apply(null,k);return c=function(t){0!==h&&zb(h);return"string"===b?Q(t):"boolean"===b?!!t:t}(c)};ca&&(La[0]=this,addEventListener("message",wa));
var Bb={_emscripten_create_wasm_worker:(a,b)=>{let c=La[Ma]=new Worker(da("app.ww.js"));c.postMessage({$ww:Ma,wasm:ka,js:f.mainScriptUrlOrBlob||_scriptDir,wasmMemory:E,sb:a,sz:b});c.onmessage=ya;return Ma++},emscripten_asm_const_int:(a,b,c)=>{Na.length=0;for(var d;d=F[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;Na.push(112==d?H[c>>2]:105==d?G[c>>2]:J[c>>3]);c+=e?8:4}return Ha[a].apply(null,Na)},emscripten_get_device_pixel_ratio:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,emscripten_get_element_css_size:(a,
b,c)=>{a=ab(a);if(!a)return-4;a=bb(a);J[b>>3]=a.width;J[c>>3]=a.height;return 0},emscripten_get_now:()=>performance.now(),emscripten_request_animation_frame:(a,b)=>requestAnimationFrame(c=>O(a)(c,b)),emscripten_resize_heap:()=>{ha("OOM")},emscripten_set_resize_callback_on_thread:(a,b,c,d)=>db(a,b,c,d),emscripten_set_touchcancel_callback_on_thread:(a,b,c,d)=>eb(a,b,c,d,25,"touchcancel"),emscripten_set_touchend_callback_on_thread:(a,b,c,d)=>eb(a,b,c,d,23,"touchend"),emscripten_set_touchmove_callback_on_thread:(a,
b,c,d)=>eb(a,b,c,d,24,"touchmove"),emscripten_set_touchstart_callback_on_thread:(a,b,c,d)=>eb(a,b,c,d,22,"touchstart"),emscripten_set_wheel_callback_on_thread:(a,b,c,d)=>(a=ab(a))?"undefined"!=typeof a.onwheel?fb(a,b,c,d):-1:-4,emscripten_wasm_worker_post_function_v:(a,b)=>{La[a].postMessage({_wsc:b,x:[]})},exitIncompatible:function(){document.querySelector("body").innerHTML="Please use a WebGPU-compatible browser."},memory:E,navigator_gpu_available:function(){return!!navigator.gpu},navigator_gpu_get_preferred_canvas_format:function(){return S.indexOf(navigator.gpu.getPreferredCanvasFormat())},
navigator_gpu_request_adapter_async:function(a,b,c){a>>=2;let d=navigator.gpu,e=[,"low-power","high-performance"][H[a]],k={};if(d){a&&(k.forceFallbackAdapter=!!H[a+1],e&&(k.powerPreference=e));function h(l){O(b)(V(l),c)}d.requestAdapter(k).then(gb(h)).catch(()=>{h()});return 1}},postCanvas:function(a,b){b=document.querySelector(Q(b)).transferControlToOffscreen();La[a].postMessage({canvas:b},[b])},renderHijackMessage:function(a){addEventListener("message",b=>{b=b.data;"canvas"in b&&(self.i=b.canvas,
console.log(self.i),f._renderAdapterInit(a))})},setOffscreenSize:function(a,b){self.i.width=a;self.i.height=b},wgpu_adapter_request_device_async:function(a,b,c,d){function e(q){q&&(q.h=[],V(q.queue));O(c)(V(q),d)}b>>=2;let k=[],h={},l=H[b];b+=2;for(let q=0;11>q;++q)l&1<<q&&k.push(hb[q]);for(let q of jb){if(l=W(b))h[q]=l;b+=2}for(let q of ib)if(l=H[b++])h[q]=l;b=H[b];T[a].requestDevice({requiredFeatures:k,requiredLimits:h,defaultQueue:b?{label:Q(b)}:void 0}).then(gb(e)).catch(()=>{e()})},wgpu_canvas_context_configure:function(a,
b){b>>=2;a=T[a];var c=a.configure,d=T[H[b]],e=S[H[b+1]],k=H[b+2],h=H[b+4],l=H[b+3];h>>=2;let q=[];for(;l--;)q.push(T[H[h++]]);c.call(a,{device:d,format:e,usage:k,viewFormats:q,colorSpace:kb[H[b+5]],alphaMode:[,"opaque","premultiplied"][H[b+6]]})},wgpu_canvas_context_get_current_texture:function(a){a=T[a].getCurrentTexture();a!=T[1]&&(X(1),T[1]=a,a.v=1,a.h=[]);return 1},wgpu_canvas_get_webgpu_context:function(){return V(self.i.getContext("webgpu"))},wgpu_command_encoder_begin_render_pass:function(a,
b){b>>=2;let c=[];var d=G[b++],e=H[b++]>>2;let k=e+6>>1,h=T[H[b]];for(;d--;)c.push(H[e]?{view:T[H[e]],depthSlice:0>G[e+1]?void 0:G[e+1],resolveTarget:T[H[e+2]],storeOp:mb[H[e+3]],loadOp:lb[H[e+4]],clearValue:[J[k],J[k+1],J[k+2],J[k+3]]}:null),e+=14,k+=7;var l;d=b+12;(e=H[d])?(e={querySet:T[e]},0<=(l=G[d+1])&&(e.beginningOfPassWriteIndex=l),0<=(l=G[d+2])&&(e.endOfPassWriteIndex=l),l=e):l=void 0;return V(T[a].beginRenderPass({colorAttachments:c,depthStencilAttachment:h?{view:h,depthLoadOp:lb[H[b+1]],
depthClearValue:I[b+2],depthStoreOp:mb[H[b+3]],depthReadOnly:!!H[b+4],stencilLoadOp:lb[H[b+5]],stencilClearValue:H[b+6],stencilStoreOp:mb[H[b+7]],stencilReadOnly:!!H[b+8]}:void 0,occlusionQuerySet:T[H[b+9]],maxDrawCount:J[b+10>>1]||void 0,timestampWrites:l}))},wgpu_device_create_bind_group:function(a,b,c,d){a=T[a];c>>=2;let e=[];for(;d--;){var k=T[H[c+1]];let h={binding:H[c],resource:k};if(k.isBuffer){k={buffer:k,offset:W(c+2)};let l=W(c+4);l&&(k.size=l);h.resource=k}e.push(h);c+=6}return Y(a.createBindGroup({layout:T[b],
entries:e}),a)},wgpu_device_create_buffer:function(a,b){a=T[a];b>>=2;b=a.createBuffer({size:W(b),usage:H[b+2],mappedAtCreation:!!H[b+3]});b.C={};b.isBuffer=1;return Y(b,a)},wgpu_device_create_command_encoder:function(a){return Y(T[a].createCommandEncoder(void 0),T[a])},wgpu_device_create_render_pipeline_async:function(a,b,c,d){let e=T[a],k=h=>{O(c)(a,Y(h,e),d)};e.createRenderPipelineAsync(wb(b)).then(gb(k)).catch(()=>{k()})},wgpu_device_create_shader_module:function(a,b){var c=T[a],d=c.createShaderModule;
var e=b>>2;b=Q(H[e]);var k=e+1;e=G[k];let h=[];k=H[k+1]>>2;let l;for(;e--;)l=H[k+1],h.push({entryPoint:Q(H[k]),layout:1<l?T[l]:l?"auto":null}),k+=2;return Y(d.call(c,{code:b,compilationHints:h}),T[a])},wgpu_device_get_queue:function(a){return T[a].queue.v},wgpu_encoder_end:function(a){T[a].end();X(a)},wgpu_encoder_finish:function(a){let b=T[a].finish();X(a);return V(b)},wgpu_encoder_set_bind_group:function(a,b,c,d,e){T[a].setBindGroup(b,T[c],H,d>>2,e)},wgpu_encoder_set_pipeline:function(a,b){T[a].setPipeline(T[b])},
wgpu_object_destroy:X,wgpu_pipeline_get_bind_group_layout:function(a,b){return V(T[a].getBindGroupLayout(b))},wgpu_queue_set_on_submitted_work_done_callback:function(a,b,c){T[a].onSubmittedWorkDone().then(()=>{O(b)(a,c)})},wgpu_queue_submit_one_and_destroy:function(a,b){T[a].submit([T[b]]);X(b)},wgpu_queue_write_buffer:function(a,b,c,d,e){T[a].writeBuffer(T[b],c,F,d,e)},wgpu_render_commands_mixin_draw:function(a,b,c,d,e){T[a].draw(b,c,d,e)},wgpu_texture_create_view_simple:function(a){return Y(T[a].createView(),
T[a])}},Z=function(){function a(c,d){Z=c.exports;Ja=Z.__indirect_function_table;qa.unshift(Z.__wasm_call_ctors);ka=d;L--;f.monitorRunDependencies?.(L);0==L&&(null!==Ba&&(clearInterval(Ba),Ba=null),M&&(c=M,M=null,c()));return Z}var b={env:Bb,wasi_snapshot_preview1:Bb};L++;f.monitorRunDependencies?.(L);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return C(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ga(b,function(c){a(c.instance,c.module)});return{}}();
f._renderAdapterInit=a=>(f._renderAdapterInit=Z.renderAdapterInit)(a);var Cb=f._main=(a,b)=>(Cb=f._main=Z.main)(a,b),cb=a=>(cb=Z.malloc)(a),va=f._emscripten_wasm_worker_initialize=(a,b)=>(va=f._emscripten_wasm_worker_initialize=Z.emscripten_wasm_worker_initialize)(a,b),yb=()=>(yb=Z.stackSave)(),zb=a=>(zb=Z.stackRestore)(a),xb=a=>(xb=Z.stackAlloc)(a);f.___start_em_js=1696;f.___stop_em_js=2322;
f.dynCall=(a,b,c)=>{a.includes("j")?(a=f["dynCall_"+a],b=c&&c.length?a.apply(null,[b].concat(c)):a.call(null,b)):b=O(b).apply(null,c);return b};f.ccall=Ab;f.cwrap=(a,b,c,d)=>{var e=!c||c.every(k=>"number"===k||"boolean"===k);return"string"!==b&&e&&!d?f["_"+a]:function(){return Ab(a,b,c,arguments,d)}};var Db;M=function Eb(){Db||Fb();Db||(M=Eb)};
function Fb(){function a(){if(!Db&&(Db=!0,f.calledRun=!0,!la)){ua();za(ra);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(Hb){var b=Cb;try{var c=b(0,0);Ka||(f.onExit?.(c),la=!0);g(c,new A(c))}catch(d){d instanceof A||"unwind"==d||g(1,d)}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)b=f.postRun.shift(),ta.unshift(b);za(ta)}}if(!(0<L))if(ca)ua();else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Aa();za(pa);0<L||
(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Hb=!0;f.noInitialRun&&(Hb=!1);Fb();
