var d;d||=typeof Module !== 'undefined' ? Module : {};var aa=Object.assign({},d),f=(a,b)=>{throw b;},ca="object"==typeof window,l="function"==typeof importScripts,n="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,da=d.$ww,_scriptDir="undefined"!=typeof document&&document.currentScript?document.currentScript.src:void 0;l?_scriptDir=self.location.href:n&&(_scriptDir=__filename);var q="";
function ea(a){return d.locateFile?d.locateFile(a,q):q+a}var fa,r,u;
if(n){var fs=require("fs"),ha=require("path");q=l?ha.dirname(q)+"/":__dirname+"/";fa=(b,c)=>{b=v(b)?new URL(b):ha.normalize(b);return fs.readFileSync(b,c?void 0:"utf8")};u=b=>{b=fa(b,!0);b.buffer||(b=new Uint8Array(b));return b};r=(b,c,e,g=!0)=>{b=v(b)?new URL(b):ha.normalize(b);fs.readFile(b,g?void 0:"utf8",(k,h)=>{k?e(k):c(g?h.buffer:h)})};process.argv.slice(2);"undefined"!=typeof module&&(module.exports=d);process.on("uncaughtException",b=>{if(!("unwind"===b||b instanceof w||b.context instanceof
w))throw b;});f=(b,c)=>{process.exitCode=b;throw c;};d.inspect=()=>"[Emscripten Module object]";let a;try{a=require("worker_threads")}catch(b){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),b;}global.Worker=a.Worker}else if(ca||l)l?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",fa=
a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(u=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),r=(a,b,c)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)};var ia=d.print||console.log.bind(console),x=d.printErr||console.error.bind(console);Object.assign(d,aa);
aa=null;d.quit&&(f=d.quit);var z;d.wasmBinary&&(z=d.wasmBinary);"object"!=typeof WebAssembly&&ja("no native wasm support detected");var A,ka,la=!1,B,C,F,G,H,ma=d.INITIAL_MEMORY||16777216;
if(d.wasmMemory)A=d.wasmMemory;else if(A=new WebAssembly.Memory({initial:ma/65536,maximum:ma/65536,shared:!0}),!(A.buffer instanceof SharedArrayBuffer))throw x("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),n&&x("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)"),Error("bad memory");
var I=A.buffer;d.HEAP8=new Int8Array(I);d.HEAP16=new Int16Array(I);d.HEAPU8=B=new Uint8Array(I);d.HEAPU16=new Uint16Array(I);d.HEAP32=C=new Int32Array(I);d.HEAPU32=F=new Uint32Array(I);d.HEAPF32=G=new Float32Array(I);d.HEAPF64=H=new Float64Array(I);ma=A.buffer.byteLength;var na=[],oa=[],pa=[],qa=[],ra=[];function sa(){if(da){let a=d;ta(a.sb,a.sz);removeEventListener("message",ua);va=va.forEach(wa);addEventListener("message",wa)}else J(oa)}function xa(){var a=d.preRun.shift();na.unshift(a)}
var K=0,ya=null,L=null;function ja(a){d.onAbort?.(a);a="Aborted("+a+")";x(a);la=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var za=a=>a.startsWith("data:application/octet-stream;base64,"),v=a=>a.startsWith("file://"),M;M="app.wasm";za(M)||(M=ea(M));function Aa(a){if(a==M&&z)return new Uint8Array(z);if(u)return u(a);throw"both async and sync fetching of the wasm failed";}
function Ba(a){if(!z&&(ca||l)){if("function"==typeof fetch&&!v(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Aa(a));if(r)return new Promise((b,c)=>{r(a,e=>b(new Uint8Array(e)),c)})}return Promise.resolve().then(()=>Aa(a))}function Ca(a,b,c){return Ba(a).then(e=>WebAssembly.instantiate(e,b)).then(e=>e).then(c,e=>{x(`failed to asynchronously prepare wasm: ${e}`);ja(e)})}
function Da(a,b){var c=M;z||"function"!=typeof WebAssembly.instantiateStreaming||za(c)||v(c)||n||"function"!=typeof fetch?Ca(c,a,b):fetch(c,{credentials:"same-origin"}).then(e=>WebAssembly.instantiateStreaming(e,a).then(b,function(g){x(`wasm streaming compile failed: ${g}`);x("falling back to ArrayBuffer instantiation");return Ca(c,a,b)}))}function w(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var va=[],N=[],Ea,O=a=>{var b=N[a];b||(a>=N.length&&(N.length=a+1),N[a]=b=Ea.get(a));return b},wa=a=>{a=n?a:a.data;let b=a._wsc;b&&O(b)(...a.x)},ua=a=>{va.push(a)},J=a=>{for(;0<a.length;)a.shift()(d)},Fa=d.noExitRuntime||!0,Ga={},Ha=1,Ia=0;function Ja(){for(var a=P.length-1;0<=a;--a)Ka(a);P=[];Q=[]}var Q=[];function La(){if(navigator.userActivation?navigator.userActivation.isActive:Ia&&Ma.s)for(var a=0;a<Q.length;++a){var b=Q[a];Q.splice(a,1);--a;b.v.apply(null,b.u)}}var P=[];
function Ka(a){var b=P[a];b.target.removeEventListener(b.h,b.m,b.i);P.splice(a,1)}function Na(a){function b(e){++Ia;Ma=a;La();a.o(e);La();--Ia}if(!a.target)return-4;if(a.l)a.m=b,a.target.addEventListener(a.h,b,a.i),P.push(a),Oa||(qa.push(Ja),Oa=!0);else for(var c=0;c<P.length;++c)P[c].target==a.target&&P[c].h==a.h&&Ka(c--);return 0}
var Oa,Ma,Pa,Qa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,R=(a,b)=>{for(var c=b+NaN,e=b;a[e]&&!(e>=c);)++e;if(16<e-b&&a.buffer&&Qa)return Qa.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,e):a.subarray(b,e));for(c="";b<e;){var g=a[b++];if(g&128){var k=a[b++]&63;if(192==(g&224))c+=String.fromCharCode((g&31)<<6|k);else{var h=a[b++]&63;g=224==(g&240)?(g&15)<<12|k<<6|h:(g&7)<<18|k<<12|h<<6|a[b++]&63;65536>g?c+=String.fromCharCode(g):(g-=65536,c+=String.fromCharCode(55296|
g>>10,56320|g&1023))}}else c+=String.fromCharCode(g)}return c},S=a=>a?R(B,a):"",Ra=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],Sa=a=>{a=2<a?a?R(B,a):"":a;return Ra[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},Ua=(a,b,c,e)=>{Pa||=Ta(36);a=Sa(a);return Na({target:a,h:"resize",l:e,o:(g=event)=>{if(g.target==a){var k=document.body;if(k){var h=Pa;C[h>>2]=g.detail;C[h+4>>2]=k.clientWidth;C[h+8>>2]=k.clientHeight;C[h+12>>2]=innerWidth;C[h+16>>2]=
innerHeight;C[h+20>>2]=outerWidth;C[h+24>>2]=outerHeight;C[h+28>>2]=pageXOffset;C[h+32>>2]=pageYOffset;O(e)(10,h,b)&&g.preventDefault()}}},i:c})},Va=[null,[],[]];String.prototype.replaceAll||(String.prototype.replaceAll=function(a,b){"?"===a&&(a="\\?");return this.replace(a instanceof RegExp?a:new RegExp(a,"g"),b)});function T(a,b,c){c=c||65;for(b=b.split("|");b[0];)a=a.replaceAll(String.fromCharCode(c++),b.pop());return[,].concat(a.split(" "))}
var U=T("r8YA8TA8SA8UALSALUALWR8YR8TR8SR8UANSANUANWRLSRLURLW V8Y V8Z V8T V8S V8U bgra8Y bgra8ZRb9e5uWRbJa2SRbJa2YR11bJuWRNSRNURNW VLS VLU VLW VNS VNU VNWB8ILYI24plusI24plus-E8INWINW-E8Q1-V-YQ1-V-ZQ2-V-YQ2-V-ZQ3-V-YQ3-V-ZQ4-r-YQ4-r-TQ5-rg-YQ5-rg-TQ6h-rgb-uWQ6h-rgb-WQ7-V-YQ7-V-ZPYPZPa1YPa1Z etc2-V8Y etc2-V8ZFr11YFr11TFrg11YFrg11TX4x4-YX4x4-ZX5x4-YX5x4-ZX5x5-YX5x5-ZX6x5-YX6x5-ZX6x6-YX6x6-ZX8x5-YX8x5-ZX8x6-YX8x6-ZX8x8-YX8x8-ZXJx5-YXJx5-ZXJx6-YXJx6-ZXJx8-YXJx8-ZXJxJ-YXJxJ-ZX12xJ-YX12xJ-ZX12x12-YX12x12-Z S8MS8KU8MU8KY8MY8KT8MT8KSLMSLKULMULKYLMYLKTLMTLKWLMWLKWN WNMWNx3 WNKSN SNMSNx3 SNKUN UNMUNx3 UNKYJ-J-J-2","unorm-srgb|unorm| astc-|float|rgba|sint|snorm|uint| rg| bc| etc2-rgb8|-AC|32|x2 |16|x4 |10| depth|-B|SC| eac-|stencil|-ESJ|-E-A| E| r"),
V={},W=1;function X(a){if(a){for(;V[++W];)2147483646<W&&(W=1);V[W]=a;return a.j=W}}function Wa(a){return b=>{try{return a(b)}catch(c){}}}
var bb=T("B-clip-control B32D-Aencil8EbcEetc2EaAc timeAamp-query indirect-firA-inAance shader-f16 rg11b10uD-rendC bgra8unorm-Aorage D32-filtC"," texture-compression-|float|erable|depth|st").slice(1),cb=T(">1D >2D >3D maxTextureArrayLayer<6<6sPlus7=<BindingsPer6 maxDynamicUniform=;DynamicS:=;SampledTexture@maxSampler@maxS:=@maxS:Texture@maxUniform=@minUniform=9inS:=9ax7=<7Attribute<7=ArrayStride max8Component<8Variable<ColorAttachment<ColorAttachmentBytesPerSample?pS:Size maxComputeInvocationsPerWorkgroup?pSizeX?pSizeY?pSizeZ","sPerShaderStage | maxComputeWorkgrou|maxTextureDimension|Buffer|s max|sPerPipelineLayout max|torage|OffsetAlignment m|InterStageShader|Vertex|BindGroup|Uniform7|8ColorAttachmen",
52).slice(1),db=T("maxUniform4Storage4BufferSize","BufferBindingSize max",52).slice(1);function eb(a){return F[a]+4294967296*F[a+1]}var fb=[,"srgb","display-p3"];function Y(a){let b=V[a];b&&(b.destroy&&b.destroy(),b.g&&b.g.forEach(Y),delete V[a])}var gb=[,"load","clear"],hb=[,"store","discard"];function ib(a,b){(a=X(a))&&b.g.push(a);return a}var jb=T("neverA equalACB notCBCalways","-equal |greater| less"),kb=T("keep zero replace invert inCBdeCBinCA deCA","crement-|clamp |wrap");
function lb(a){return{compare:jb[F[a]],failOp:kb[F[a+1]],depthFailOp:kb[F[a+2]],passOp:kb[F[a+3]]}}var mb=T("add Areverse-Amin max","subtract "),nb=T("zero one BEB BDEBD AEA ADEAD BD-saturated CEC"," one-minus-|-alpha|constant|src|dst");function ob(a){return{operation:mb[F[a]],srcFactor:nb[F[a+1]],dstFactor:nb[F[a+2]]}}function pb(a,b){let c={};for(;b--;)c[S(F[a>>2])]=H[a+8>>3],a+=16;return c}
var qb=T("A16 A32","uint"),rb=T("pointDADAB CDCB","-list |triangle|-strip|line"),sb=T("1B 2dCA AC3d","-array |d 2d|cube"),tb=T("all stencilA depthA","-only");da&&(Ga[0]=this,addEventListener("message",ua));
var ub={_emscripten_create_wasm_worker:(a,b)=>{let c=Ga[Ha]=new Worker(ea("app.ww.js"));c.postMessage({$ww:Ha,wasm:ka,js:d.mainScriptUrlOrBlob||_scriptDir,wasmMemory:A,sb:a,sz:b});c.onmessage=wa;return Ha++},emscripten_get_device_pixel_ratio:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,emscripten_get_element_css_size:(a,b,c)=>{a=Sa(a);if(!a)return-4;a=0>Ra.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};H[b>>3]=a.width;H[c>>3]=a.height;return 0},emscripten_get_now:()=>performance.now(),
emscripten_request_animation_frame_loop:(a,b)=>{function c(e){O(a)(e,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},emscripten_resize_heap:()=>{ja("OOM")},emscripten_set_canvas_element_size:(a,b,c)=>{a=Sa(a);if(!a)return-4;a.width=b;a.height=c;return 0},emscripten_set_resize_callback_on_thread:(a,b,c,e)=>Ua(a,b,c,e),emscripten_wasm_worker_post_function_v:(a,b)=>{Ga[a].postMessage({_wsc:b,x:[]})},fd_write:(a,b,c,e)=>{for(var g=0,k=0;k<c;k++){var h=F[b>>2],m=F[b+4>>2];b+=8;for(var p=
0;p<m;p++){var t=B[h+p],y=Va[a];0===t||10===t?((1===a?ia:x)(R(y,0)),y.length=0):y.push(t)}g+=m}F[e>>2]=g;return 0},memory:A,navigator_gpu_get_preferred_canvas_format:function(){return U.indexOf(navigator.gpu.getPreferredCanvasFormat())},navigator_gpu_request_adapter_async:function(a,b,c){a>>=2;let e=navigator.gpu,g=[,"low-power","high-performance"][F[a]],k={};if(e){a&&(k.forceFallbackAdapter=!!F[a+1],g&&(k.powerPreference=g));function h(m){O(b)(X(m),c)}e.requestAdapter(k).then(Wa(h)).catch(()=>{h()});
return 1}},wgpu_adapter_request_device_async:function(a,b,c,e){function g(p){p&&(p.g=[],X(p.queue));O(c)(X(p),e)}b>>=2;let k=[],h={},m=F[b];b+=2;for(let p=0;11>p;++p)m&1<<p&&k.push(bb[p]);for(let p of db){if(m=eb(b))h[p]=m;b+=2}for(let p of cb)if(m=F[b++])h[p]=m;b=F[b];V[a].requestDevice({requiredFeatures:k,requiredLimits:h,defaultQueue:b?{label:b?R(B,b):""}:void 0}).then(Wa(g)).catch(()=>{g()})},wgpu_canvas_context_configure:function(a,b){b>>=2;a=V[a];var c=a.configure,e=V[F[b]],g=U[F[b+1]],k=F[b+
2],h=F[b+4],m=F[b+3];h>>=2;let p=[];for(;m--;)p.push(V[F[h++]]);c.call(a,{device:e,format:g,usage:k,viewFormats:p,colorSpace:fb[F[b+5]],alphaMode:[,"opaque","premultiplied"][F[b+6]]})},wgpu_canvas_context_get_current_texture:function(a){a=V[a].getCurrentTexture();a!=V[1]&&(Y(1),V[1]=a,a.j=1,a.g=[]);return 1},wgpu_canvas_get_webgpu_context:function(a){return X(document.querySelector(a?R(B,a):"").getContext("webgpu"))},wgpu_command_encoder_begin_render_pass:function(a,b){b>>=2;let c=[];var e=C[b++],
g=F[b++]>>2;let k=g+6>>1,h=V[F[b]];for(;e--;)c.push(F[g]?{view:V[F[g]],depthSlice:0>C[g+1]?void 0:C[g+1],resolveTarget:V[F[g+2]],storeOp:hb[F[g+3]],loadOp:gb[F[g+4]],clearValue:[H[k],H[k+1],H[k+2],H[k+3]]}:null),g+=14,k+=7;var m;e=b+12;(g=F[e])?(g={querySet:V[g]},0<=(m=C[e+1])&&(g.beginningOfPassWriteIndex=m),0<=(m=C[e+2])&&(g.endOfPassWriteIndex=m),m=g):m=void 0;return X(V[a].beginRenderPass({colorAttachments:c,depthStencilAttachment:h?{view:h,depthLoadOp:gb[F[b+1]],depthClearValue:G[b+2],depthStoreOp:hb[F[b+
3]],depthReadOnly:!!F[b+4],stencilLoadOp:gb[F[b+5]],stencilClearValue:F[b+6],stencilStoreOp:hb[F[b+7]],stencilReadOnly:!!F[b+8]}:void 0,occlusionQuerySet:V[F[b+9]],maxDrawCount:H[b+10>>1]||void 0,timestampWrites:m}))},wgpu_device_create_command_encoder:function(a){return ib(V[a].createCommandEncoder(void 0),V[a])},wgpu_device_create_render_pipeline:function(a,b){var c=V[a],e=c.createRenderPipeline,g=[];let k=[],h=b>>2,m=C[h+2],p=F[h+3]>>2,t=h+6;b=t+5;let y=b+17,D=y+3,zb=C[D+2],E=F[D+3]>>2,Xa=F[b++],
Ya=F[y],Za=F[D],$a=F[D+6];for(;m--;){let ab=[],Ab=C[p],ba=F[p+1]>>2;for(;Ab--;)ab.push({offset:eb(ba),shaderLocation:F[ba+2],format:U[F[ba+3]]}),ba+=4;g.push({arrayStride:eb(p+2),stepMode:[,"vertex","instance"][F[p+4]],attributes:ab});p+=6}for(;zb--;)k.push(F[E]?{format:U[F[E]],blend:F[E+1]?{color:ob(E+1),alpha:ob(E+4)}:void 0,writeMask:F[E+7]}:null),E+=8;g={vertex:{module:V[F[h]],entryPoint:S(F[h+1])||void 0,buffers:g,constants:pb(F[h+5],C[h+4])},primitive:{topology:rb[F[t]],stripIndexFormat:qb[F[t+
1]],frontFace:[,"ccw","cw"][F[t+2]],cullMode:[,"none","front","back"][F[t+3]],unclippedDepth:!!F[t+4]},layout:1<$a?V[$a]:"auto"};Xa&&(g.depthStencil={format:U[Xa],depthWriteEnabled:!!F[b++],depthCompare:jb[F[b++]],stencilReadMask:F[b++],stencilWriteMask:F[b++],depthBias:C[b++],depthBiasSlopeScale:G[b++],depthBiasClamp:G[b++],stencilFront:lb(b),stencilBack:lb(b+4),clampDepth:!!F[b+8]});Ya&&(g.multisample={count:Ya,mask:F[y+1],alphaToCoverageEnabled:!!F[y+2]});Za&&(g.fragment={module:V[Za],entryPoint:S(F[D+
1])||void 0,targets:k,constants:pb(F[D+5],C[D+4])});return ib(e.call(c,g),V[a])},wgpu_device_create_shader_module:function(a,b){var c=V[a],e=c.createShaderModule;var g=b>>2;b=S(F[g]);var k=g+1;g=C[k];let h=[];k=F[k+1]>>2;let m;for(;g--;)m=F[k+1],h.push({entryPoint:S(F[k]),layout:1<m?V[m]:m?"auto":null}),k+=2;return ib(e.call(c,{code:b,compilationHints:h}),V[a])},wgpu_device_get_queue:function(a){return V[a].queue.j},wgpu_encoder_end:function(a){V[a].end();Y(a)},wgpu_encoder_finish:function(a){let b=
V[a].finish();Y(a);return X(b)},wgpu_encoder_set_pipeline:function(a,b){V[a].setPipeline(V[b])},wgpu_queue_submit_one_and_destroy:function(a,b){V[a].submit([V[b]]);Y(b)},wgpu_render_commands_mixin_draw:function(a,b,c,e,g){V[a].draw(b,c,e,g)},wgpu_texture_create_view:function(a,b){b>>=2;return ib(V[a].createView(b?{format:U[F[b]],dimension:sb[F[b+1]],aspect:tb[F[b+2]],baseMipLevel:C[b+3],mipLevelCount:C[b+4],baseArrayLayer:C[b+5],arrayLayerCount:C[b+6]}:void 0),V[a])}},Z=function(){function a(c,e){Z=
c.exports;Ea=Z.__indirect_function_table;oa.unshift(Z.__wasm_call_ctors);ka=e;K--;d.monitorRunDependencies?.(K);0==K&&(null!==ya&&(clearInterval(ya),ya=null),L&&(c=L,L=null,c()));return Z}var b={env:ub,wasi_snapshot_preview1:ub};K++;d.monitorRunDependencies?.(K);if(d.instantiateWasm)try{return d.instantiateWasm(b,a)}catch(c){return x(`Module.instantiateWasm callback failed with error: ${c}`),!1}Da(b,function(c){a(c.instance,c.module)});return{}}(),vb=d._main=(a,b)=>(vb=d._main=Z.main)(a,b),Ta=a=>
(Ta=Z.malloc)(a),ta=d._emscripten_wasm_worker_initialize=(a,b)=>(ta=d._emscripten_wasm_worker_initialize=Z.emscripten_wasm_worker_initialize)(a,b);d.dynCall_jiji=(a,b,c,e,g)=>(d.dynCall_jiji=Z.dynCall_jiji)(a,b,c,e,g);var wb;L=function xb(){wb||yb();wb||(L=xb)};
function yb(){function a(){if(!wb&&(wb=!0,d.calledRun=!0,!la)){sa();J(pa);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(Bb){var b=vb;try{var c=b(0,0);Fa||(d.onExit?.(c),la=!0);f(c,new w(c))}catch(e){e instanceof w||"unwind"==e||f(1,e)}}if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;)b=d.postRun.shift(),ra.unshift(b);J(ra)}}if(!(0<K))if(da)sa();else{if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)xa();J(na);0<K||(d.setStatus?
(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);a()},1)):a())}}if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();var Bb=!0;d.noInitialRun&&(Bb=!1);yb();
